Criação de Matrizes com Numpy

In [23]:
import numpy as np

np.array: Converter matrizes em NParray

In [24]:
#para criar uma matriz podemos usar o comando array ou mat

linha = np.array([1,2,3])
coluna = np.array([[1],[2],[3]])
vetor = np.array([[1,2,3],[4,5,6]])

vetor_b = np.mat([[1,2,3],[1,2,3]])
print(vetor)
print(vetor_b)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [1 2 3]]


In [25]:
#selecionar uma linha da matriz
vetor[1]

array([4, 5, 6])

In [26]:
#selecionar uma célular (valor) da matriz
vetor[1,2]

6

In [27]:
#selecionar um intervalo
print(vetor[1,1:])
print(vetor[1,:2])

[5 6]
[4 5]


In [28]:
print(vetor[:,:2])

[[1 2]
 [4 5]]


In [29]:
#selecionar o último elemento utilizando índice negativo
print(vetor[-1,:])

[4 5 6]


Calculos com vetores

In [30]:
vetor += 100
print(vetor)

[[101 102 103]
 [104 105 106]]


In [31]:
vetor *= 2
print(vetor)

[[202 204 206]
 [208 210 212]]


In [32]:
print(np.max(vetor[0]))
print(np.min(vetor[:,1]))
print(np.average(vetor[:]))

206
204
207.0


Biblioteca RANDOM

randint: Gerar lista de números randomicos

In [33]:
import random

#O random.seed serve para determinar um ponto de partida para escolha do número aleatório, garantindo que em toda execução saia o mesmo número aleatório.
random.seed(55)
random.randint(1,100)

12

choice: Selecionar um elemento aleatório de uma lista

In [34]:
estados = ['RJ','SP','MG','AM','MT','MS']
random.choice(estados)

'SP'

shuffle: Embaralhar ordem de listas numéricas ou de texto 

In [37]:
lista = [carac for carac in "Essa é minha frase"] #primeiro converto a string para uma lista
random.shuffle(lista) #Irá gerar uma lista com as letras embaralhadas
frase_embaralhada = "".join(lista) #Vai juntar a lista como uma string novamente
frase_embaralhada

'aahnsif rsEé saem '